import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { build } from 'esbuild';

/**
 * Embeds the console UI (console-design §7.5 self-containment) into the tsup
 * bundle: dist ships only .js files, so packages/plugin/src/console/ui/* is compiled into
 * string constants here. Re-run after touching packages/plugin/src/console/ui/.
 *
 *   pnpm gen:ui-assets
 *
 * `app.js` is bundled rather than embedded verbatim, because it imports
 * `runskein/fold` (ADR 0006) and that has to travel with it. The bundle
 * settings are the CSP contract in code: §7.5 serves `script-src 'self'` with
 * no `unsafe-eval`, so nothing here may emit `eval`/`new Function`, no source
 * map is produced (a map would also carry the fold sources into the asset), and
 * the output is a plain IIFE with no module loader.
 */
const root = process.cwd();
const uiDir = join(root, 'packages', 'plugin', 'src', 'console', 'ui');

const bundled = await build({
  entryPoints: [join(uiDir, 'app.js')],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2022',
  minify: true,
  sourcemap: false,
  legalComments: 'none',
  write: false,
  // The console UI is a second bundle with its own dependency graph — it
  // inlines `runskein/fold`, which the server build never sees. A generator
  // that consulted only tsup's metafile would attribute nothing for code the
  // console ships (ADR 0041 step 20).
  metafile: true,
});
// Outside `dist/`, for two reasons: `tsup` runs after this with `clean: true`
// and would wipe it, and a metafile is a build input rather than something the
// tarball should carry.
await mkdir(join(root, '.build'), { recursive: true });
await writeFile(join(root, '.build', 'metafile-ui.json'), JSON.stringify(bundled.metafile), 'utf8');
// Keep the generated bundle's historical strict-mode prologue. The package
// split must not change the execution mode of the CSP-governed browser asset.
const js = bundled.outputFiles[0] === undefined
  ? undefined
  : `"use strict";${bundled.outputFiles[0].text}`;
if (js === undefined) throw new Error('UI bundle produced no output');
// Fail the build rather than the browser console: a CSP violation from a
// bundler default surfaces nowhere else until someone opens the page.
for (const forbidden of ['eval(', 'new Function(', '//# sourceMappingURL']) {
  if (js.includes(forbidden)) throw new Error(`UI bundle contains ${forbidden}, which console-design §7.5 forbids under script-src 'self'`);
}

const [html, css, font] = await Promise.all([
  readFile(join(uiDir, 'index.html'), 'utf8'),
  readFile(join(uiDir, 'app.css'), 'utf8'),
  readFile(join(uiDir, 'fonts', 'PTMono-Regular.woff2')),
]);

const output = `/**
 * GENERATED by scripts/gen-ui-assets.ts from packages/plugin/src/console/ui/ — do not edit.
 * The console UI is embedded so the single-file dist bundle stays
 * self-contained (console-design §7.5); the font travels as base64.
 */
export const UI_INDEX_HTML = ${JSON.stringify(html)};

export const UI_APP_CSS = ${JSON.stringify(css)};

export const UI_APP_JS = ${JSON.stringify(js)};

export const UI_FONT_WOFF2_BASE64 = ${JSON.stringify(font.toString('base64'))};
`;

await writeFile(join(root, 'packages', 'plugin', 'src', 'console', 'ui-assets.ts'), output);
console.log(`ui-assets.ts: html ${html.length}B, css ${css.length}B, js ${js.length}B, font ${font.length}B`);
